[global]
workname = "GocaProject"
jobname = "GocaScan"
useragent = "Goca Metadata Scanner"
threads = 1
loglevel = "info"
plugins = ["all"]

[scrapper]
domain = "example.com"
depth = 1
threshold = 1
save = false

[dorker]
term = "foo"
maxpages = 1
threshold = 1
engines = ["all"]
save = false

[database]
file = ""

[plugin]
list = false